name: bugsee_flutter
description: Bugsee Flutter SDK
version: 1.0.2
author: Bugsee <support@bugsee.com>
homepage: https://github.com/bugsee/flutter

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  stack_trace: ">=1.0.0 <2.0.0"
  crypto: "3.0.1"
  convert: "3.0.0"
  uuid: "3.0.4"
  package_info: "2.0.0"

flutter:
  plugin:
    androidPackage: com.bugsee
    pluginClass: BugseePlugin
